# ROBOT IP-ADDRESS
ROBOT_IP = "141.252.29.30"

# TELEMETRY VARIABLES
TELEMETRY_IP = "212.204.150.138"
TELEMETRY_PORT = "5356"

# LEFT MAIN ENGINE
LEFT_MOTOR_ID = 0
LEFT_MOTOR_PWM = 27
LEFT_MOTOR_A = 22
LEFT_MOTOR_B = 23

# RIGHT MAIN ENGINE
RIGHT_MOTOR_ID = 1
RIGHT_MOTOR_PWM = 17    
RIGHT_MOTOR_A = 24
RIGHT_MOTOR_B = 25

# REMOTE CONTROLLER INPUTS
X_LEFT = "x_l"
Y_LEFT = "y_l"
X_RIGHT = "x_r"
Y_RIGHT = "y_r"
CLICK_LEFT = "c_l"
CLICK_RIGHT = "c_r"
POWER = "p"
MANUAL = "m"
CLAW = "claw"
NECK = "neck"
AUTO_MODE = "mode"
AUTO_MODE_SINGLE = "single"
AUTO_MODE_LINE = "line"
AUTO_MODE_CAPS = "caps"
AUTO_MODE_VISION = "vision"

# SERVO VARIABLES
HEAD_ID = 0
NECK_ID = 1
HAND_ID = 11
HAND_OPEN = 650
HAND_CLOSED = 1023
HAND_STEP_SPEED = 25

EYEBROW_PWM_FREQUENCY = 50
LEFT_EYEBROW_ID = 0
RIGHT_EYEBROW_ID = 1

# LOAD CELL VARIABLES
SCALE_DAT = 20
SCALE_CLK = 21
SCALE_OFFSET = 0    # TODO: Change to correct value.
SCALE_RATIO = 0     # TODO: Change to correct value. (Measured weight / real item weight)